import sys

from semiwrap.tool.create_imports import ImportCreator, UpdateInit


def test_create_preserves_exclude_directives_and_omits_exports(tmp_path, monkeypatch):
    package = tmp_path / "exclude_directives_pkg"
    package.mkdir()
    exclude_line = "# - exclude Baz, Foo, Unknown" + "  "
    (package / "__init__.py").write_text(
        f"""# autogenerated by 'robotpy-build create-imports exclude_directives_pkg exclude_directives_pkg._compiled'
# - exclude Foo, Bar
{exclude_line}
from ._compiled import Bar, Baz, Foo, FooBar, Keep

__all__ = ["Bar", "Baz", "Foo", "FooBar", "Keep"]
"""
    )
    (package / "_compiled.py").write_text(
        """class Foo:
    pass

class Bar:
    pass

class Baz:
    pass

class FooBar:
    pass

class Keep:
    pass
"""
    )
    monkeypatch.syspath_prepend(str(tmp_path))

    try:
        ImportCreator().create(
            "exclude_directives_pkg",
            "exclude_directives_pkg._compiled",
            True,
            None,
        )
    finally:
        for name in list(sys.modules):
            if name == "exclude_directives_pkg" or name.startswith(
                "exclude_directives_pkg."
            ):
                del sys.modules[name]

    assert (package / "__init__.py").read_text() == (
        f"""# autogenerated by 'semiwrap create-imports exclude_directives_pkg exclude_directives_pkg._compiled'
# - exclude Foo, Bar
{exclude_line}
from ._compiled import FooBar, Keep

__all__ = ["FooBar", "Keep"]
"""
    )


def test_create_supports_excluding_every_export(tmp_path, monkeypatch):
    package = tmp_path / "exclude_all_pkg"
    package.mkdir()
    (package / "__init__.py").write_text(
        """# autogenerated by 'semiwrap create-imports exclude_all_pkg exclude_all_pkg._compiled'
# - exclude Foo
from ._compiled import Foo

__all__ = ["Foo"]
"""
    )
    (package / "_compiled.py").write_text(
        """class Foo:
    pass
"""
    )
    monkeypatch.syspath_prepend(str(tmp_path))

    try:
        creator = ImportCreator()
        creator.create("exclude_all_pkg", "exclude_all_pkg._compiled", True, None)
        creator.create("exclude_all_pkg", "exclude_all_pkg._compiled", True, None)
    finally:
        for name in list(sys.modules):
            if name == "exclude_all_pkg" or name.startswith("exclude_all_pkg."):
                del sys.modules[name]

    assert (package / "__init__.py").read_text() == (
        """# autogenerated by 'semiwrap create-imports exclude_all_pkg exclude_all_pkg._compiled'
# - exclude Foo
__all__ = []
"""
    )


def test_update_init_applies_exclude_directives(tmp_path, monkeypatch):
    (tmp_path / "pyproject.toml").write_text(
        """[tool.semiwrap]
update_init = ["update_init_pkg update_init_pkg._compiled"]
"""
    )
    package = tmp_path / "update_init_pkg"
    package.mkdir()
    (package / "__init__.py").write_text(
        """# autogenerated by 'semiwrap create-imports update_init_pkg update_init_pkg._compiled'
# - exclude Internal
from ._compiled import Internal, Public

__all__ = ["Internal", "Public"]
"""
    )
    (package / "_compiled.py").write_text(
        """class Internal:
    pass

class Public:
    pass
"""
    )
    monkeypatch.chdir(tmp_path)
    monkeypatch.syspath_prepend(str(tmp_path))

    try:
        UpdateInit().run(None)
    finally:
        for name in list(sys.modules):
            if name == "update_init_pkg" or name.startswith("update_init_pkg."):
                del sys.modules[name]

    assert (package / "__init__.py").read_text() == (
        """# autogenerated by 'semiwrap create-imports update_init_pkg update_init_pkg._compiled'
# - exclude Internal
from ._compiled import Public

__all__ = ["Public"]
"""
    )
