import posixpath
import subprocess
import sys
import typing
import types
import pathlib

from ..pyproject import PyProject


class ImportCreator:
    @classmethod
    def add_subparser(cls, parent_parser, subparsers):
        parser = subparsers.add_parser(
            "create-imports",
            help="Generate suitable imports for a module. Prefer using update-init",
            parents=[parent_parser],
        )
        parser.add_argument("base", help="Ex: wpiutil")
        parser.add_argument("compiled", nargs="?", help="Ex: wpiutil._impl.wpiutil")
        parser.add_argument(
            "--write", "-w", action="store_true", help="Modify existing __init__.py"
        )
        parser.add_argument(
            "--override_output_file",
            type=pathlib.Path,
            help="If specified, will write the updated file to this location instead of making the change in place. Only used if --write is set.",
        )
        return parser

    def _rel(self, base: str, compiled: str) -> str:
        base = posixpath.join(*base.split("."))
        compiled = posixpath.join(*compiled.split("."))
        elems = posixpath.relpath(compiled, base).split("/")
        elems = ["" if e == ".." else e for e in elems]
        return f".{'.'.join(elems)}"

    def run(self, args):
        self.create(args.base, args.compiled, args.write, args.override_output_file)

    def _find_excludes(
        self, content: str, begin_statements: typing.Iterable[str]
    ) -> typing.Tuple[typing.Set[str], typing.List[str]]:
        for begin_stmt in begin_statements:
            startidx = content.find(begin_stmt)
            if startidx == -1:
                continue

            line_end = content.find("\n", startidx)
            if line_end == -1:
                break

            excludes: typing.Set[str] = set()
            exclude_lines = []
            line_start = line_end + 1
            while content.startswith("# - exclude ", line_start):
                line_end = content.find("\n", line_start)
                if line_end == -1:
                    line_end = len(content)

                line = content[line_start:line_end]
                exclude_lines.append(line)
                excludes.update(
                    name.strip()
                    for name in line[len("# - exclude ") :].split(",")
                    if name.strip()
                )
                line_start = line_end + 1

            return excludes, exclude_lines

        return set(), []

    def create(
        self,
        base: str,
        compiled: typing.Optional[str],
        write: bool,
        override_output_file: typing.Optional[pathlib.Path],
    ):
        # Runtime Dependency Check
        try:
            import black
        except:
            print(
                "Error, The following module is required to run this tool: black",
                file=sys.stderr,
            )
            return 1

        if not compiled:
            compiled = f"{base}._{base.split('.')[-1]}"
            print(f"CHK base={base} compiled={compiled} (auto)")
        else:
            print(f"CHK base={base} compiled={compiled}")

        # TODO: could probably generate this from parsed code, but seems hard
        ctx: typing.Dict[str, typing.Any] = {}
        exec(f"from {compiled} import *", {}, ctx)
        for k in list(ctx.keys()):
            if isinstance(ctx[k], types.ModuleType):
                del ctx[k]

        relimport = self._rel(base, compiled)

        stmt_compiled = "" if not compiled else f" {compiled}"
        begin_stmt = f"# autogenerated by 'semiwrap create-imports {base}"
        old_begin_stmt = f"# autogenerated by 'robotpy-build create-imports {base}"

        fcontent = orig_content = fname = None
        exclude_lines: typing.List[str] = []
        if write:
            fctx: typing.Dict[str, typing.Any] = {}
            exec(f"from {base} import __file__", {}, fctx)
            fname = fctx["__file__"]

            with open(fname) as fp:
                fcontent = orig_content = fp.read()

            excludes, exclude_lines = self._find_excludes(
                fcontent, (begin_stmt, old_begin_stmt)
            )
            for exclude in excludes:
                ctx.pop(exclude, None)

        header = f"{begin_stmt}{stmt_compiled}'"
        if exclude_lines:
            header = "\n".join((header, *exclude_lines))
        names = sorted(ctx.keys())
        stmt_lines = []
        if names:
            all_names = '", "'.join(names)
            stmt_lines.append(f"from {relimport} import {','.join(names)}")
            stmt_lines.append(f'__all__ = ["{all_names}"]')
        else:
            stmt_lines.append("__all__ = []")
        stmt = "\n".join(stmt_lines) + "\n"

        formatted_stmt = subprocess.check_output(
            [sys.executable, "-m", "black", "-", "-q"], input=stmt.encode("utf-8")
        ).decode("utf-8")
        content = f"{header}\n{formatted_stmt}"

        if write:
            assert fcontent is not None
            assert orig_content is not None
            assert fname is not None

            # Find the beginning statement
            idx = startidx = fcontent.find(begin_stmt)
            if startidx == -1:
                idx = startidx = fcontent.find(old_begin_stmt)

            if startidx != -1:
                idx = fcontent.find("\n", idx)
                if idx != -1:
                    idx += 1
                    while fcontent.startswith("# - exclude ", idx):
                        idx = fcontent.find("\n", idx)
                        if idx == -1:
                            break
                        idx += 1

                for to_find in ("__all__", "[", "]", "\n"):
                    if idx == -1:
                        startidx = -1
                        break
                    idx = fcontent.find(to_find, idx)
                    if idx == -1:
                        startidx = -1
                        break

            if startidx == -1:
                # If not present, just append and let the user figure it out
                fcontent = fcontent + "\n" + content
            else:
                fcontent = fcontent[:startidx] + content + fcontent[idx + 1 :]

            # Always write the file if override_output_file is specified.
            # Othewise only write if the contents have changed.
            if override_output_file or fcontent != orig_content:
                fname = override_output_file or fname
                with open(fname, "w") as fp:
                    fp.write(fcontent)
                print("MOD", base)
            else:
                print("OK", base)

        else:
            print(content)


class UpdateInit:
    @classmethod
    def add_subparser(cls, parent_parser, subparsers):
        parser = subparsers.add_parser(
            "update-init",
            help="Updates __init__.py files using settings from tool.semiwrap.update_init",
            parents=[parent_parser],
        )
        return parser

    def run(self, args):
        project = PyProject().project

        if project.update_init is None:
            print("[tool.semiwrap].update_init not set", file=sys.stderr)
            return 1

        ic = ImportCreator()

        for to_update in project.update_init:
            if " " in to_update:
                base, compiled = to_update.split(" ", 1)
            else:
                base = to_update
                compiled = None

            ic.create(base, compiled, True, None)
