from .buffer import RenderBuffer
from .context import HeaderContext, TemplateInstanceContext
from .namespace_utils import generated_qualname, namespace_scope

from .render_cls_prologue import render_class_prologue


def render_template_inst_cpp(
    hctx: HeaderContext, tmpl_data: TemplateInstanceContext
) -> str:
    r = RenderBuffer()
    render_class_prologue(r, hctx)

    tmpl_params = ", ".join(str(p) for p in tmpl_data.params)
    binder_type = generated_qualname(
        tmpl_data.namespace, f"bind_{tmpl_data.full_cpp_name_identifier}"
    )

    r.write_trim(
        f"""
        #include <trampolines/{tmpl_data.header_name}>
        #include "{hctx.hname}_tmpl.hpp"
        """
    )
    r.writeln()

    with namespace_scope(r, tmpl_data.namespace, anonymous=True):
        r.write_trim(
            f"""
            using BindType = {binder_type}<{tmpl_params}>;
            static std::unique_ptr<BindType> inst;
            """
        )

    r.writeln()
    with namespace_scope(r, tmpl_data.namespace, generated=True):
        r.write_trim(
            f"""
            {tmpl_data.binder_typename}::{tmpl_data.binder_typename}(py::module &m, const char * clsName)
            {{
              inst = std::make_unique<BindType>(m, clsName);
            }}

            void {tmpl_data.binder_typename}::finish(const char *set_doc, const char *add_doc)
            {{
              inst->finish(set_doc, add_doc);
              inst.reset();
            }}
            """
        )

    r.writeln()
    return r.getvalue()


def render_template_inst_hpp(hctx: HeaderContext) -> str:
    r = RenderBuffer()
    r.write_trim(
        """
        // This file is autogenerated. DO NOT EDIT
        #pragma once
        #include <semiwrap.h>
        """
    )

    for tmpl_data in hctx.template_instances:
        r.writeln()
        with namespace_scope(r, tmpl_data.namespace, generated=True):
            r.write_trim(
                f"""
                struct {tmpl_data.binder_typename} {{
                  {tmpl_data.binder_typename}(py::module &m, const char * clsName);
                  void finish(const char *set_doc, const char *add_doc);
                }};
                """
            )

    return r.getvalue()
